-- ============================================
-- Seed de equipamentos
-- ============================================

INSERT INTO equipment (name, name_en, category) VALUES
('Peso corporal', 'Bodyweight', 'nenhum'),
('Nenhum equipamento', 'None', 'nenhum'),
('Barra olympica', 'Olympic bar', 'barras'),
('Barra EZ', 'EZ bar', 'barras'),
('Barra W', 'W bar', 'barras'),
('Anilhas', 'Plates', 'peso_livre'),
('Halteres', 'Dumbbells', 'peso_livre'),
('Kettlebell', 'Kettlebell', 'peso_livre'),
('Medicine ball', 'Medicine ball', 'peso_livre'),
('Sandbag', 'Sandbag', 'peso_livre'),
('Banco', 'Bench', 'bancos'),
('Banco inclinado', 'Incline bench', 'bancos'),
('Banco romano', 'Roman chair', 'bancos'),
('Rack', 'Power rack', ' racks'),
('Smith machine', 'Smith machine', ' racks'),
('Half rack', 'Half rack', ' racks'),
('Polia alta', 'High pulley', 'cabos'),
('Polia baixa', 'Low pulley', 'cabos'),
('Crossover', 'Crossover', 'cabos'),
('Cabo', 'Cable', 'cabos'),
('Leg press', 'Leg press', 'máquinas'),
('Hack squat', 'Hack squat', 'máquinas'),
('Cadeira extensora', 'Leg extension', 'máquinas'),
('Mesa flexora', 'Leg curl', 'máquinas'),
('Cadeira adutora', 'Hip adduction', 'máquinas'),
('Cadeira abdutora', 'Hip abduction', 'máquinas'),
('Máquina de supino', 'Chest press machine', 'máquinas'),
('Peck deck', 'Peck deck', 'máquinas'),
('Crucifixo machine', 'Fly machine', 'máquinas'),
('Máquina de remada', 'Rowing machine', 'máquinas'),
('Lat pulldown', 'Lat pulldown', 'máquinas'),
('Máquina de ombro', 'Shoulder press machine', 'máquinas'),
('Tríceps machine', 'Triceps machine', 'máquinas'),
('Rosca machine', 'Biceps curl machine', 'máquinas'),
('Barra fixa', 'Pull-up bar', 'barras_fixas'),
('Barra fixa supinada', 'Chin-up bar', 'barras_fixas'),
('Dip station', 'Dip station', 'barras_fixas'),
('Elástico', 'Resistance band', 'elasticos'),
('TRX', 'TRX', 'suspensão'),
('Corda de pular', 'Jump rope', 'cardio'),
('Colchonete', 'Mat', 'acessorios'),
('Foam roller', 'Foam roller', 'acessorios'),
('Apoio para abdominal', 'Ab wheel', 'acessorios'),
('Skipping', 'Skipping', 'cardio');

-- ============================================
-- Seed de exercícios
-- ============================================

INSERT INTO exercises (name, alt_name, description, instructions, primary_muscle, secondary_muscles, movement_pattern, is_unilateral, is_compound, is_bodyweight, load_unit, has_distance, has_time, tags) VALUES
-- Pernas
('Agachamento livre', 'Squat', 'Agachamento com barra nas costas', 'Posicione a barra nos trapézios, desça até paralelo ao chão e suba.', 'Quadríceps', ARRAY['Glúteos', 'Isquiotibiais', 'Core'], 'agachamento', false, true, false, 'kg', false, false, ARRAY['pernas', 'força']),
('Agachamento frontal', 'Front Squat', 'Agachamento com barra na frente', 'Barra apoiada nos ombros, cotovelos altos.', 'Quadríceps', ARRAY['Glúteos', 'Core'], 'agachamento', false, true, false, 'kg', false, false, ARRAY['pernas', 'força']),
('Agachamento sumô', 'Sumo Squat', 'Agachamento com stance larga', 'Pés apontados para fora, stance larga.', 'Quadríceps', ARRAY['Glúteos', 'Adutores'], 'agachamento', false, true, false, 'kg', false, false, ARRAY['pernas', 'força']),
('Leg press', 'Leg Press', 'Pressão de pernas', 'Pressione a plataforma com os pés.', 'Quadríceps', ARRAY['Glúteos', 'Isquiotibiais'], 'flexão de joelho', false, true, false, 'kg', false, false, ARRAY['pernas', 'máquina']),
('Hack squat', 'Hack Squat', 'Agachamento hack', 'Agachamento na máquina hack com pés altos.', 'Quadríceps', ARRAY['Glúteos'], 'agachamento', false, true, false, 'kg', false, false, ARRAY['pernas', 'máquina']),
('Cadeira extensora', 'Leg Extension', 'Extensão de pernas', 'Estenda as pernas na máquina.', 'Quadríceps', ARRAY[], 'extensão de joelho', false, false, false, 'kg', false, false, ARRAY['pernas', 'máquina', 'isolado']),
('Mesa flexora', 'Leg Curl', 'Flexão de joelhos', 'Flexione os joelhos na mesa flexora.', 'Isquiotibiais', ARRAY['Glúteos'], 'flexão de joelho', false, false, false, 'kg', false, false, ARRAY['pernas', 'máquina', 'isolado']),
('Stiff', 'Deadlift', 'Stiff com barra', 'Flexione os quadris com joelhos levemente flexionados.', 'Isquiotibiais', ARRAY['Glúteos', 'Core'], 'hinge', false, true, false, 'kg', false, false, ARRAY['pernas', 'costas', 'força']),
('Romano', 'Romanian Deadlift', 'RDL', 'Deadlift rumeno com foco nos isquiotibiais.', 'Isquiotibiais', ARRAY['Glúteos', 'Core'], 'hinge', false, true, false, 'kg', false, false, ARRAY['pernas', 'costas', 'força']),
('Elevação pélvica', 'Hip Thrust', 'Hip thrust', 'Pressione os quadris para cima com as costas no banco.', 'Glúteos', ARRAY['Isquiotibiais'], 'hinge', false, true, false, 'kg', false, false, ARRAY['glúteos', 'força']),
('Afundo', 'Lunge', 'Avanço', 'Dê um passo à frente e baixe o joelho.', 'Quadríceps', ARRAY['Glúteos', 'Isquiotibiais'], 'agachamento', true, true, false, 'kg', false, false, ARRAY['pernas', 'unilateral']),
('Afundo walked', 'Walking Lunge', 'Avanço caminhando', 'Avance alternando pernas.', 'Quadríceps', ARRAY['Glúteos', 'Isquiotibiais'], 'agachamento', true, true, false, 'kg', false, false, ARRAY['pernas', 'unilateral']),
('Agachamento búlgaro', 'Bulgarian Split Squat', 'Splits squat', 'Uma perna atrás no banco, agache.', 'Quadríceps', ARRAY['Glúteos'], 'agachamento', true, true, false, 'kg', false, false, ARRAY['pernas', 'unilateral']),
('Elevação de calcanhar', 'Calf Raise', 'Elevação de panturrilha', 'Suba nas pontas dos pés.', 'Panturrilha', ARRAY[], 'flexão de joelho', false, false, false, 'kg', false, false, ARRAY['panturrilha', 'isolado']),
('Agachamento com salto', 'Jump Squat', 'Plyometric squat', 'Agache e Salto.', 'Quadríceps', ARRAY['Glúteos', 'Panturrilha'], 'agachamento', false, true, true, 'bodyweight', false, false, ARRAY['pernas', 'plyo']),
('Agachamento bodyweight', 'Bodyweight Squat', 'Agachamento sem peso', 'Agache sem peso adicional.', 'Quadríceps', ARRAY['Glúteos', 'Isquiotibiais'], 'agachamento', false, true, true, 'bodyweight', false, false, ARRAY['pernas', 'calistenia']),
('Agachamento profundo', 'Deep Squat', 'Agachamento profundo', 'Agache até o fundo.', 'Quadríceps', ARRAY['Glúteos'], 'agachamento', false, true, true, 'bodyweight', false, false, ARRAY['pernas', 'mobilidade']),

-- Peito
('Supino reto', 'Bench Press', 'Supino com barra', 'Aperte a barra no peito com cotovelos a 45 graus.', 'Peito', ARRAY['Ombros', 'Tríceps'], 'empurrar horizontal', false, true, false, 'kg', false, false, ARRAY['peito', 'força']),
('Supino inclinado', 'Incline Bench Press', 'Supino no banco inclinado', 'Banco inclinado a 30-45 graus.', 'Peito superior', ARRAY['Ombros', 'Tríceps'], 'empurrar horizontal', false, true, false, 'kg', false, false, ARRAY['peito', 'força']),
('Supino declinado', 'Decline Bench Press', 'Supino no banco declinado', 'Banco inclinado para baixo.', 'Peito inferior', ARRAY['Tríceps'], 'empurrar horizontal', false, true, false, 'kg', false, false, ARRAY['peito']),
('Supino com halteres', 'Dumbbell Bench Press', 'Supino com dumbbells', 'Use halteres para maior amplitude.', 'Peito', ARRAY['Ombros', 'Tríceps'], 'empurrar horizontal', false, true, false, 'kg', false, false, ARRAY['peito', 'força']),
('Supino inclinado com halteres', 'Incline Dumbbell Press', 'Supino inclinado com halteres', 'Halteres com banco inclinado.', 'Peito superior', ARRAY['Ombros', 'Tríceps'], 'empurrar horizontal', false, true, false, 'kg', false, false, ARRAY['peito']),
('Crucifixo reto', 'Dumbbell Fly', 'Abertura com halteres', 'Abra os braços com halteres.', 'Peito', ARRAY[], 'empurrar horizontal', false, false, false, 'kg', false, false, ARRAY['peito', 'isolado']),
('Crucifixo inclinado', 'Incline Dumbbell Fly', 'Abertura inclinada', 'Abertura no banco inclinado.', 'Peito superior', ARRAY[], 'empurrar horizontal', false, false, false, 'kg', false, false, ARRAY['peito', 'isolado']),
('Peck deck', 'Pec Deck', 'Máquina peck deck', 'Feche a máquina com os braços.', 'Peito', ARRAY[], 'empurrar horizontal', false, false, false, 'kg', false, false, ARRAY['peito', 'máquina']),
('Crossover alto', 'High Cable Fly', 'Crossover de cima', 'Cruze os cables por cima.', 'Peito', ARRAY[], 'empurrar horizontal', false, false, false, 'kg', false, false, ARRAY['peito', 'cabo']),
('Crossover baixo', 'Low Cable Fly', 'Crossover de baixo', 'Cruze os cables por baixo.', 'Peito inferior', ARRAY[], 'empurrar horizontal', false, false, false, 'kg', false, false, ARRAY['peito', 'cabo']),
('Flexão de braço', 'Push-up', 'Flexão tradicional', 'Flexione os braços mantendo o corpo reto.', 'Peito', ARRAY['Ombros', 'Tríceps', 'Core'], 'empurrar horizontal', false, true, true, 'bodyweight', false, false, ARRAY['peito', 'calistenia']),
('Flexão diamante', 'Diamond Push-up', 'Flexão com mãos juntas', 'Mãos em formato de diamante.', 'Tríceps', ARRAY['Peito'], 'empurrar horizontal', false, true, true, 'bodyweight', false, false, ARRAY['peito', 'tríceps', 'calistenia']),
('Flexão wide', 'Wide Push-up', 'Flexão com mãos largas', 'Mãos mais largas que os ombros.', 'Peito', ARRAY['Ombros'], 'empurrar horizontal', false, true, true, 'bodyweight', false, false, ARRAY['peito', 'calistenia']),
('Mergulho', 'Dip', 'Mergulho nas paralelas', 'Desça e suba nas paralelas.', 'Peito', ARRAY['Tríceps', 'Ombros'], 'empurrar vertical', false, true, true, 'bodyweight', false, false, ARRAY['peito', 'tríceps', 'calistenia']),
('Peck deck machine', 'Machine Chest Press', 'Supino na máquina', 'Pressione na máquina.', 'Peito', ARRAY['Ombros', 'Tríceps'], 'empurrar horizontal', false, true, false, 'kg', false, false, ARRAY['peito', 'máquina']),

-- Costas
('Puxada supinada', 'Pull-up', 'Puxada na barra', 'Puxe o corpo até a barra.', 'Dorso', ARRAY['Bíceps', 'Core'], 'puxar vertical', false, true, true, 'bodyweight', false, false, ARRAY['costas', 'força']),
('Puxada pronada', 'Chin-up', 'Puxada com pegada neutra', 'Puxe com mãos supinadas.', 'Dorso', ARRAY['Bíceps'], 'puxar vertical', false, true, true, 'bodyweight', false, false, ARRAY['costas', 'bíceps']),
('Puxada na máquina', 'Lat Pulldown', 'Puxada no cabo', 'Puxe a barra para o peito.', 'Dorso', ARRAY['Bíceps'], 'puxar vertical', false, true, false, 'kg', false, false, ARRAY['costas', 'máquina']),
('Puxada aberta', 'Wide Grip Pulldown', 'Puxada com pegada larga', 'Pegada mais larga que os ombros.', 'Dorso', ARRAY[], 'puxar vertical', false, true, false, 'kg', false, false, ARRAY['costas', 'máquina']),
('Puxada unilateral', 'Single Arm Pulldown', 'Puxada unilateral', 'Puxe com um braço.', 'Dorso', ARRAY['Bíceps'], 'puxar vertical', true, true, false, 'kg', false, false, ARRAY['costas', 'unilateral']),
('Remada curvada', 'Bent Over Row', 'Remada curvada', 'Remada com barra curvado.', 'Dorso', ARRAY['Bíceps', 'Core'], 'puxar horizontal', false, true, false, 'kg', false, false, ARRAY['costas', 'força']),
('Remada cavalinho', 'Barbell Row', 'Remada no estilo cavalo', 'Torax apoiado no banco.', 'Dorso', ARRAY['Bíceps'], 'puxar horizontal', false, true, false, 'kg', false, false, ARRAY['costas', 'força']),
('Remada com halter', 'Dumbbell Row', 'Remada com halter', 'Uma mão apoiada, puxe o halter.', 'Dorso', ARRAY['Bíceps'], 'puxar horizontal', true, true, false, 'kg', false, false, ARRAY['costas', 'unilateral']),
('Remada T', 'T-Bar Row', 'Remada T', 'Remada com barra em T.', 'Dorso', ARRAY['Bíceps', 'Core'], 'puxar horizontal', false, true, false, 'kg', false, false, ARRAY['costas', 'força']),
('Remada na máquina', 'Seated Cable Row', 'Remada no cabo', 'Remada sentado no cabo.', 'Dorso', ARRAY['Bíceps'], 'puxar horizontal', false, true, false, 'kg', false, false, ARRAY['costas', 'cabo']),
('Remada baixa', 'Face Pull', 'Puxada facial', 'Puxe a corda para o rosto.', 'Posterior deltoide', ARRAY['Trapézio', 'Rombóides'], 'puxar horizontal', false, false, false, 'kg', false, false, ARRAY['costas', 'ombros']),
('Puxada ao rosto', 'Straight Arm Pulldown', 'Puxada de tríceps', 'Braços retos, puxe para baixo.', 'Dorso', ARRAY[], 'puxar vertical', false, false, false, 'kg', false, false, ARRAY['costas', 'cabo']),
('Barra fixa', 'Dead Hang', 'Barra fixa estático', 'Fique pendurado na barra.', 'Dorso', ARRAY['Antebraços'], 'puxar vertical', false, false, true, 'bodyweight', false, true, ARRAY['costas', 'força']),
('Good morning', 'Good Morning', 'Good morning', 'Flexione o quadril com barra.', 'Isquiotibiais', ARRAY['Glúteos', 'Core'], 'hinge', false, true, false, 'kg', false, false, ARRAY['costas', 'pernas']),

-- Ombros
('Desenvolvimento', 'Overhead Press', 'Pressão militar', 'Pressione a barra acima da cabeça.', 'Deltoide', ARRAY['Tríceps', 'Core'], 'empurrar vertical', false, true, false, 'kg', false, false, ARRAY['ombros', 'força']),
('Desenvolvimento com halteres', 'Dumbbell Shoulder Press', 'Pressão com halteres', 'Pressione halteres acima da cabeça.', 'Deltoide', ARRAY['Tríceps'], 'empurrar vertical', false, true, false, 'kg', false, false, ARRAY['ombros', 'força']),
('Desenvolvimento Arnold', 'Arnold Press', 'Pressão Arnold', 'Rotacione os halteres ao pressionar.', 'Deltoide', ARRAY['Tríceps'], 'empurrar vertical', false, true, false, 'kg', false, false, ARRAY['ombros']),
('Elevação lateral', 'Lateral Raise', 'Prancha lateral', 'Levante os braços lateralmente.', 'Deltoide lateral', ARRAY[], 'empurrar vertical', false, false, false, 'kg', false, false, ARRAY['ombros', 'isolado']),
('Elevação frontal', 'Front Raise', 'Prancha frontal', 'Levante os braços para frente.', 'Deltoide frontal', ARRAY[], 'empurrar vertical', false, false, false, 'kg', false, false, ARRAY['ombros', 'isolado']),
('Elevação posterior', 'Rear Delt Fly', 'Prancha posterior', 'Levante os braços para trás.', 'Posterior deltoide', ARRAY['Trapézio'], 'puxar horizontal', false, false, false, 'kg', false, false, ARRAY['ombros', 'isolado']),
('Crucifixo invertido', 'Reverse Pec Deck', 'Peck deck inverso', 'Abra a máquina para trás.', 'Posterior deltoide', ARRAY['Trapézio'], 'puxar horizontal', false, false, false, 'kg', false, false, ARRAY['ombros', 'máquina']),
('Upright row', 'Upright Row', 'Remada vertical', 'Puxe a barra para o queixo.', 'Deltoide', ARRAY['Trapézio'], 'puxar vertical', false, true, false, 'kg', false, false, ARRAY['ombros']),
('Shrugs', 'Shrugs', 'Encolher ombros', 'Encolha os ombros com peso.', 'Trapézio', ARRAY[], 'core', false, false, false, 'kg', false, false, ARRAY['ombros', 'isolado']),
('Pike push-up', 'Pike Push-up', 'Flexão pike', 'Flexão com quadril elevado.', 'Deltoide', ARRAY['Tríceps'], 'empurrar vertical', false, true, true, 'bodyweight', false, false, ARRAY['ombros', 'calistenia']),

-- Bíceps
('Rosca direta', 'Barbell Curl', 'Rosca com barra', 'Encurve os cotovelos com barra.', 'Bíceps', ARRAY['Antebraços'], 'flexão de cotovelo', false, false, false, 'kg', false, false, ARRAY['bíceps', 'força']),
('Rosca com halter', 'Dumbbell Curl', 'Rosca com halteres', 'Encurve os cotovelos com halteres.', 'Bíceps', ARRAY['Antebraços'], 'flexão de cotovelo', true, false, false, 'kg', false, false, ARRAY['bíceps']),
('Rosca martelo', 'Hammer Curl', 'Rosca martelo', 'Pegada neutra.', 'Bíceps', ARRAY['Antebraços'], 'flexão de cotovelo', true, false, false, 'kg', false, false, ARRAY['bíceps']),
('Rosca concentrada', 'Concentration Curl', 'Rosca concentrada', 'Cotovelo apoiado na coxa.', 'Bíceps', ARRAY[], 'flexão de cotovelo', true, false, false, 'kg', false, false, ARRAY['bíceps', 'isolado']),
('Rosca na polia', 'Cable Curl', 'Rosca no cabo', 'Rosca no cabo baixo.', 'Bíceps', ARRAY[], 'flexão de cotovelo', false, false, false, 'kg', false, false, ARRAY['bíceps', 'cabo']),
('Rosca Scott', 'Scott Curl', 'Rosca no banco scott', 'Braços apoiados no banco scott.', 'Bíceps', ARRAY[], 'flexão de cotovelo', false, false, false, 'kg', false, false, ARRAY['bíceps', 'isolado']),
('Rosca蜘蛛', 'Spider Curl', 'Rosca invertida', 'Braços pendurados no banco inclinado.', 'Bíceps', ARRAY[], 'flexão de cotovelo', false, false, false, 'kg', false, false, ARRAY['bíceps']),
('Rosca 21', '21s', 'Rosca 21', '7 reps metade, 7 completo, 7 outro lado.', 'Bíceps', ARRAY[], 'flexão de cotovelo', false, false, false, 'kg', false, false, ARRAY['bíceps']),

-- Tríceps
('Tríceps na polia', 'Triceps Pushdown', 'Puxada de tríceps', 'Puxe o cabo para baixo.', 'Tríceps', ARRAY[], 'extensão de cotovelo', false, false, false, 'kg', false, false, ARRAY['tríceps', 'cabo']),
('Tríceps no cabo com corda', 'Triceps Rope Pushdown', 'Corda no cabo', 'Puxe a corda para baixo.', 'Tríceps', ARRAY[], 'extensão de cotovelo', false, false, false, 'kg', false, false, ARRAY['tríceps', 'cabo']),
('Tríceps overhead', 'Overhead Triceps Extension', 'Extensão overhead', 'Extensão acima da cabeça.', 'Tríceps', ARRAY[], 'extensão de cotovelo', false, false, false, 'kg', false, false, ARRAY['tríceps']),
('Tríceps kickback', 'Triceps Kickback', 'Chute de tríceps', 'Estenda o braço para trás.', 'Tríceps', ARRAY[], 'extensão de cotovelo', true, false, false, 'kg', false, false, ARRAY['tríceps']),
('Mergulho de tríceps', 'Triceps Dip', 'Mergulho de tríceps', 'Mergulho focado nos tríceps.', 'Tríceps', ARRAY['Peito'], 'extensão de cotovelo', false, true, true, 'bodyweight', false, false, ARRAY['tríceps', 'calistenia']),
('Flexão diamante tríceps', 'Diamond Push-up', 'Flexão diamante', 'Foco nos tríceps.', 'Tríceps', ARRAY['Peito'], 'empurrar horizontal', false, true, true, 'bodyweight', false, false, ARRAY['tríceps', 'calistenia']),
('Close grip bench', 'Close Grip Bench Press', 'Supino fechado', 'Supino com mãos próximas.', 'Tríceps', ARRAY['Peito'], 'empurrar horizontal', false, true, false, 'kg', false, false, ARRAY['tríceps']),
('Skull crusher', 'Skull Crusher', 'Skull crusher', 'Extensão de tríceps deitado.', 'Tríceps', ARRAY[], 'extensão de cotovelo', false, false, false, 'kg', false, false, ARRAY['tríceps']),
('Tríceps na máquina', 'Triceps Machine', 'Máquina de tríceps', 'Extensão na máquina.', 'Tríceps', ARRAY[], 'extensão de cotovelo', false, false, false, 'kg', false, false, ARRAY['tríceps', 'máquina']),

-- Core
('Prancha', 'Plank', 'Prancha isométrica', 'Mantenha o corpo reto.', 'Core', ARRAY['Ombros'], 'core', false, false, true, 'bodyweight', false, true, ARRAY['core', 'isometrico']),
('Prancha lateral', 'Side Plank', 'Prancha lateral', 'Mantenha o corpo de lado.', 'Oblíquo', ARRAY['Core'], 'core', true, false, true, 'bodyweight', false, true, ARRAY['core', 'isometrico']),
('Abdominal tradicional', 'Crunch', 'Abdominal', 'Levante o tronco.', 'Reto abdominal', ARRAY[], 'core', false, false, true, 'bodyweight', false, false, ARRAY['core']),
('Elevação de perna', 'Leg Raise', 'Elevação de pernas', 'Levante as pernas deitado.', 'Reto abdominal', ARRAY['Hip flexores'], 'core', false, false, true, 'bodyweight', false, false, ARRAY['core']),
('Perna suspensa', 'Hanging Leg Raise', 'Perna suspensa', 'Levante as pernas pendurado.', 'Reto abdominal', ARRAY['Hip flexores'], 'core', false, false, true, 'bodyweight', false, false, ARRAY['core']),
('Abdominal na polia', 'Cable Crunch', 'Abdominal no cabo', 'Puxe o cabo com o abdômen.', 'Reto abdominal', ARRAY[], 'core', false, false, false, 'kg', false, false, ARRAY['core']),
('Abdominal wheel', 'Ab Wheel Rollout', 'Roda abdominal', 'Rode a roda para frente.', 'Core', ARRAY['Ombros'], 'core', false, false, true, 'bodyweight', false, false, ARRAY['core']),
('Mountain climber', 'Mountain Climber', 'Escalador', 'Alterne as pernas rapidamente.', 'Core', ARRAY['Quadríceps'], 'core', false, false, true, 'bodyweight', false, false, ARRAY['core', 'cardio']),
('Russian twist', 'Russian Twist', 'Giro russo', 'Gire o tronco para os lados.', 'Oblíquo', ARRAY['Reto abdominal'], 'core', false, false, true, 'bodyweight', false, false, ARRAY['core']),
('Dead bug', 'Dead Bug', 'Dead bug', 'Alternar braços e pernas deitado.', 'Core', ARRAY[], 'core', false, false, true, 'bodyweight', false, false, ARRAY['core']),

-- Cardio/Condicionamento
('Corrida', 'Running', 'Corrida', 'Corra em esteira ou externo.', 'Quadríceps', ARRAY['Panturrilha', 'Core'], 'locomover', false, false, false, 'bodyweight', false, true, ARRAY['cardio', 'aerobico']),
('Burpee', 'Burpee', 'Burpee', 'Agachamento + pulo + flexão + salto.', 'Corpo todo', ARRAY[], 'condicionamento', false, true, true, 'bodyweight', false, false, ARRAY['cardio', 'hiit']),
('Kettlebell swing', 'Kettlebell Swing', 'Balanço de kettlebell', 'Balançe o kettlebell.', 'Glúteos', ARRAY['Isquiotibiais', 'Core', 'Ombros'], 'hinge', false, true, false, 'kg', false, false, ARRAY['cardio', 'força', 'hiit']),
('Battle ropes', 'Battle Ropes', 'Corda de guerra', 'Balançe as cordas.', 'Ombros', ARRAY['Core', 'Braços'], 'condicionamento', false, false, false, 'kg', false, false, ARRAY['cardio', 'hiit']),
('Box jump', 'Box Jump', 'Salto no box', 'Salte sobre o box.', 'Quadríceps', ARRAY['Glúteos', 'Panturrilha'], 'locomover', false, true, false, 'bodyweight', false, false, ARRAY['cardio', 'plyo']),
('Slam ball', 'Ball Slam', 'Slam de bola', 'Jogue a bola no chão.', 'Core', ARRAY['Ombros', 'Braços'], 'condicionamento', false, true, false, 'kg', false, false, ARRAY['cardio', 'hiit']),
('Farmer walk', 'Farmer Walk', 'Caminhada do fazendeiro', 'Caminhe com pesos.', 'Core', ARRAY['Antebraços', 'Trapézio'], 'carregar', false, true, false, 'kg', false, false, ARRAY['cardio', 'força']),
('Pular corda', 'Jump Rope', 'Pular corda', 'Pule corda.', 'Panturrilha', ARRAY['Core', 'Ombros'], 'locomover', false, false, true, 'bodyweight', false, false, ARRAY['cardio']);
